alias bashrc="code ~/.bash_aliases && source ~/.bashrc"
alias i3conf="code ~/.config/i3/config"
alias up1="cd .."
alias up2="cd ../.."
alias up3="cd ../../.."
alias up4="cd ../../../.."
alias up5="cd ../../../../.."
alias diff="colordiff"